name: Continuous Integration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        auth-token: ${{ secrets.GH_TOKEN }}
        registry-url: "https://npm.pkg.github.com"
        scope: taimoormk
        node-version: ${{ matrix.node-version }}
    - name: yarn, lint, build, & test 
      run: |
        yarn
        yarn lint
        yarn build
        yarn test
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_REGISTRY_URL: https://npm.pkg.github.com
